travis:
  secure:
    BINSTAR_TOKEN: YmB7HY+dV8lMP0vDgKOek1BYYYnO4XS5S3znGmcJ+GCddfEqHWC5fGos2w2B311p8smWY93ciciu7YHNoUbxOAS3KSlea9R//uxvYf1KokylkbOjo2c353MUap7eENVQ6i6OMdTMO+oc4qQlYFWIRnl7mSChlGHmi3BdZohfG14iD4GuOoQTRU3E8C8t5ZvfRZvkkA2gYJMwHYOEv5lCoG5x02h9C0WOWgQ5kqFlXMQeoDscslyCjG5beUvpP5BNKmdPrgDsUbb9ffi79ZhRdhgljyUgiA1cfmfuB5Pc4NO41VVxH7Iuudc+iQZJV8CASs5vVCr7QfUfpSjyWOtyBKmGR53KCByRIkZURdbo3kKHIYOXkv0erkiNvy71ZE7DNW6dDRJPqxB3T4EBvaPp0eHQpebFwflAJikVSJr2wUqMvC6OQyo9cg07Y9/mcF7vV2pOtm3xGUbYY5/l2ENyg6W+SA+Z2G1azNeZRMQmGTsDddvu6q//q3xPiSXlsKWW4NO+TtONEwAYiMXr4upV7X+N5TKR2Gd1rFXCQu8Br5CZfFAZ8hz2i7FU2KZHrNdd6OdIXAAVFRbPA7ZQsYgr2HcQ/aVmCOANYWXCgCoy2N9ORyZckX2mta8HUE7dn5gbcuJqEbVmgVsaTqKAZ4vzjtXzEnipo54pPCiJKwJYOyA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
